export const TOGGLE_MODAL_CONFIGURATOR =
	'configurator/TOGGLE_MODAL_CONFIGURATOR';
export const GET_CONFIGURATOR = 'configurator/GET_CONFIGURATOR';
export const SET_ITEM_CONFIGURATOR = 'configurator/SET_ITEM_CONFIGURATOR';
export const SET_DISABLED_CONFIGURATOR =
	'configurator/SET_DISABLED_CONFIGURATOR';
export const SET_OPTIONS_CONFIGURATOR = 'configurator/SET_OPTIONS_CONFIGURATOR';
export const OPEN_CONFIGURATOR = 'configurator/OPEN_CONFIGURATOR';
export const SET_CHARACTERISTICS = 'configurator/SET_CHARACTERISTICS';
export const LOADING_CONFIGURATOR = 'configurator/LOADING_CONFIGURATOR';
export const SET_HASH = 'configurator/SET_HASH';
export const SELECT_CONFIGURATOR = 'configurator/SELECT_CONFIGURATOR';
export const NEW_CONFIGURATOR = 'configurator/NEW_CONFIGURATOR';
export const SET_MASK = 'configurator/SET_MASK';
export const SET_VALUE_BASE = 'configurator/SET_VALUE_BASE';
export const SET_VALUE_OPTIONAL = 'configurator/SET_VALUE_OPTIONAL';
export const SET_RESPONSE_VALUES = 'configurator/SET_RESPONSE_VALUES';
export const SET_RESPONSE_BODY = 'configurator/SET_RESPONSE_BODY';
export const SET_VANT = 'configurator/SET_VANT';
export const SET_SELECT_RESPONSE = 'configurator/SET_SELECT_RESPONSE';

export default {
	TOGGLE_MODAL_CONFIGURATOR,
	GET_CONFIGURATOR,
	SET_ITEM_CONFIGURATOR,
	SET_DISABLED_CONFIGURATOR,
	SET_OPTIONS_CONFIGURATOR,
	OPEN_CONFIGURATOR,
	LOADING_CONFIGURATOR,
	SET_HASH,
	SELECT_CONFIGURATOR,
	NEW_CONFIGURATOR,
	SET_MASK,
	SET_VALUE_BASE,
	SET_RESPONSE_VALUES,
	SET_RESPONSE_BODY,
	SET_VALUE_OPTIONAL,
	SET_VANT,
	SET_SELECT_RESPONSE,
};
